/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.clssLoaiPhong;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Random;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

import Model.HotelModel;

/**
 *
 * @author ADMIN
 */
public class frmDKPhong extends javax.swing.JFrame {

    public frmDSPhong phongKhachSan;

    /**
     * Creates new form frmChonMon
     */

    public void SB(String maSoPhong) {
        this.txtSoPhong.setText(maSoPhong);
    }

    public frmDKPhong() {
        initComponents();
        HienThiDSPhong();
        // HienThiDSHoaDon();
    }

    public void HienThiDSPhong() {
        Vector<clssLoaiPhong> ds = new Vector<clssLoaiPhong>();

        int ketqua = CSDL.tbPhong.DSPhong(ds);
        if (ketqua == -1) {
            JOptionPane.showMessageDialog(this, "Loi ket noi sql");
            return;
        } else if (ketqua == -2) {
            JOptionPane.showMessageDialog(this, "Loi sql");
            return;
        } else {
            DefaultTableModel dtm = (DefaultTableModel) this.tblGia.getModel();
            dtm.setRowCount(0);
            for (clssLoaiPhong dss : ds)
                dtm.addRow(new Object[] { dss.getLoaiPhong(), dss.getDonGia() });
        }
    }

    public void HienThiDSHoaDon() {
        Connection conn = CSDL.Database.ConnectDatabase();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Loi ket noi");
            return;
        }
        String soPhong = this.txtSoPhong.getText();
        String sql = "select * from phong_" + soPhong;

        try {
            PreparedStatement stm = conn.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) this.tblHoaDon.getModel();
            dtm.setNumRows(0);
            while (rs.next()) {

                int setID = rs.getInt("ID");
                String loaiPhong = rs.getString("loaiPhong");
                float donGia = rs.getFloat("donGia");
                int soGio = rs.getInt("soGio");
                String hoaDon = rs.getString("hoaDon");
                String ngayNhanPhong = rs.getString("ngayNhan");
                String ngayTraPhong = rs.getString("ngayTra");
                int maHoaDon = rs.getInt("maHoaDon");
                String tenKhachHang = rs.getString("tenKhachHang");
                String ngayLapHoaDon = rs.getString("ngayLapHoaDon");
                float thanhTien = rs.getFloat("thanhTien");
                int soNgayO = rs.getInt("soNgayO");

                dtm.addRow(new Object[] { setID, loaiPhong, Float.toString(donGia), Integer.toString(soGio), hoaDon,
                        ngayNhanPhong, ngayTraPhong, Integer.toString(maHoaDon), tenKhachHang, ngayLapHoaDon,
                        Float.toString(thanhTien), soNgayO });

                this.txtLoaiPhong.setText("");
                this.txtDonGiaPhong.setText("");
                this.txtSoGioSD.setText("");
                this.txtLoaiHoaDon.setText("");
                this.txtNgayDen.setText("");
                this.txtNgayTraPhong.setText("");
                this.txtMaHoaDon.setText("");
                this.txtTenKhachHang.setText("");
                this.txtNgayLapHoaDon.setText("");
                this.txtThanhTien.setText("");

            }

        } catch (SQLException ex) {
            Logger.getLogger(frmDKPhong.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi sql " + ex.getMessage());
            return;
        }
    }

    public boolean ktso(String so) {
        try {
            float i = Float.parseFloat(so);
            return true;
        } catch (Exception ex) {
            return false;
        }
    }

    public float TongTien() {
        String tt = this.txtTongTien.getText();
        float tongtien = Float.parseFloat(tt);
        return tongtien;
    }

    public int SoPhong() {
        String soPhong = this.txtSoPhong.getText();
        int SB = Integer.parseInt(soPhong);
        return SB;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblGia = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSoGioSD = new javax.swing.JTextField();
        txtThanhTien = new javax.swing.JTextField();
        btnThemHoaDon = new javax.swing.JButton();
        btnThanhTien = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        btnLamMoi = new javax.swing.JButton();
        btnTongTien = new javax.swing.JButton();
        txtTongTien = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        btnDSHoaDon = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSoPhong = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtLoaiPhong = new javax.swing.JTextField();
        txtDonGiaPhong = new javax.swing.JTextField();
        txtLoaiHoaDon = new javax.swing.JTextField();
        txtNgayDen = new javax.swing.JTextField();
        txtNgayTraPhong = new javax.swing.JTextField();
        txtMaHoaDon = new javax.swing.JTextField();
        txtTenKhachHang = new javax.swing.JTextField();
        txtNgayLapHoaDon = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }

            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lập hoá đơn");

        tblGia.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Loại Phòng", "Đơn giá"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblGiaNgayMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblGia);

        jLabel2.setText("Loại phòng");

        jLabel3.setText("Đơn giá:");

        jLabel4.setText("Số giờ:");

        txtThanhTien.setEditable(false);

        btnThemHoaDon.setText("Thêm vào hóa đơn");
        btnThemHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBill(evt);
            }
        });

        btnThanhTien.setText("Thành tiền:");
        btnThanhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhTienActionPerformed(evt);
            }
        });

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "STT", "Loại Phòng", "Đơn giá", "Số giờ sử dụng", "Loại hoá đơn", "Ngày nhận phòng",
                        "Ngày trả phòng", "Mã hoá đơn", "Tên khách hàng", "Ngày lập hoá đơn", "Thành tiền",
                        "S\u1ED1 ng\u00E0y \u1EDF"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblHoaDon);

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnTongTien.setText("Tổng tiền");
        btnTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTongTienActionPerformed(evt);
            }
        });

        txtTongTien.setEditable(false);

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        btnDSHoaDon.setText("Lấy danh sách hóa đơn");
        btnDSHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDSHoaDonActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jButton1.setText("Xóa hết danh sách");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Phòng");

        txtSoPhong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSoPhong.setForeground(new java.awt.Color(0, 0, 255));
        txtSoPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSoPhong.setText("Số Phòng");

        jLabel9.setText("Loại hoá đơn:");

        jLabel10.setText("Ngày nhận phòng:");

        jLabel11.setText("Ngày trả phòng:");

        jLabel12.setText("Mã hoá đơn:");

        jLabel13.setText("Tên khách hàng:");

        jLabel14.setText("Ngày Lập Hoá Đơn:");

        txtLoaiPhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiPhongActionPerformed(evt);
            }
        });

        jMenu1.setText("Hệ thống");

        jMenuItem1.setText("Quay lại");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Đăng xuất");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Thoát");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                layout.createSequentialGroup()
                                                                                        .addComponent(btnThanhTien)
                                                                                        .addGap(18, 18, 18)
                                                                                        .addComponent(txtThanhTien,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                120,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(jScrollPane1,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                375,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(58, 58, 58)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel2)
                                                                                        .addComponent(jLabel3)
                                                                                        .addComponent(jLabel4)
                                                                                        .addComponent(jLabel9))
                                                                                .addGap(53, 53, 53)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                        false)
                                                                                        .addComponent(txtSoGioSD,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                120, Short.MAX_VALUE)
                                                                                        .addComponent(txtLoaiPhong)
                                                                                        .addComponent(txtDonGiaPhong)))
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(jLabel13)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel12)
                                                                                        .addGroup(
                                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                layout.createSequentialGroup()
                                                                                                        .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(
                                                                                                                        jLabel10)
                                                                                                                .addComponent(
                                                                                                                        jLabel11))
                                                                                                        .addPreferredGap(
                                                                                                                javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                                        .addGroup(layout
                                                                                                                .createParallelGroup(
                                                                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                        false)
                                                                                                                .addComponent(
                                                                                                                        txtLoaiHoaDon,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        120,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(
                                                                                                                        txtNgayDen,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        120,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(
                                                                                                                        txtNgayTraPhong,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                                        120,
                                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                                        .addGroup(layout.createParallelGroup(
                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                false)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(btnThemHoaDon)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                Short.MAX_VALUE)
                                                                                        .addComponent(btnLamMoi))
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addComponent(jLabel14)
                                                                                        .addPreferredGap(
                                                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                        .addGroup(layout
                                                                                                .createParallelGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(
                                                                                                        txtNgayLapHoaDon,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                        120,
                                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                .addGroup(
                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                        layout.createParallelGroup(
                                                                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                                                                false)
                                                                                                                .addComponent(
                                                                                                                        txtTenKhachHang,
                                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                                        120,
                                                                                                                        Short.MAX_VALUE)
                                                                                                                .addComponent(
                                                                                                                        txtMaHoaDon,
                                                                                                                        javax.swing.GroupLayout.Alignment.TRAILING))))))
                                                                .addGap(43, 43, 43))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(jLabel5)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(btnTongTien,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        133,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(txtTongTien)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(btnThanhToan))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGap(0, 208, Short.MAX_VALUE)
                                                                                .addComponent(btnDSHoaDon)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(btnXoa,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        86,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(jButton1,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        202,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(71, 71, 71))
                                                                        .addComponent(jScrollPane3))
                                                                .addGap(10, 10, 10))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtSoPhong)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE))))))
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 212,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDong)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtSoPhong))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(btnDSHoaDon)
                                                        .addComponent(btnXoa)
                                                        .addComponent(jButton1)
                                                        .addComponent(txtLoaiPhong,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane3,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 0,
                                                                Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel3)
                                                                        .addComponent(txtDonGiaPhong,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(9, 9, 9)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(txtSoGioSD,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel9)
                                                                        .addComponent(txtLoaiHoaDon,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(15, 15, 15)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel10)
                                                                        .addComponent(txtNgayDen,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel11)
                                                                        .addComponent(txtNgayTraPhong,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel12)
                                                                        .addComponent(txtMaHoaDon,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel13)
                                                                        .addComponent(txtTenKhachHang,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(txtNgayLapHoaDon,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jLabel14))
                                                                .addGap(0, 0, Short.MAX_VALUE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(58, 58, 58)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnTongTien)
                                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnThanhToan)
                                                .addComponent(btnThanhTien))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnThemHoaDon)
                                                        .addComponent(btnLamMoi))
                                                .addComponent(txtThanhTien, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtLoaiPhongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtLoaiPhongActionPerformed
        // TODO add your handling code here:
    }

    private void tblGiaNgayMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
        int i = this.tblGia.getSelectedRow();
        String tenkhach = (String) this.tblGia.getValueAt(i, 0);
        float dongia = (float) this.tblGia.getValueAt(i, 1);

        this.txtLoaiPhong.setText(tenkhach);
        this.txtDonGiaPhong.setText(Float.toString(dongia));

        this.txtSoGioSD.setText("1");

        this.txtThanhTien.setText("");
    }

    private void btnThanhTienActionPerformed(java.awt.event.ActionEvent evt) {

        String soGio = this.txtSoGioSD.getText();
        String loaiPhong = this.txtLoaiPhong.getText();
        String getNgayNhan = this.txtNgayDen.getText();
        String getNgayTra = this.txtNgayTraPhong.getText();

        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate dateNhan = LocalDate.parse(getNgayNhan, dateTimeFormatter);
        LocalDate dateTra = LocalDate.parse(getNgayTra, dateTimeFormatter);

        int getDateNhanInt = dateNhan.getDayOfMonth();
        int gettDateTraInt = dateTra.getDayOfMonth();

        int soNgayOLai = gettDateTraInt - getDateNhanInt;

        if (loaiPhong.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa chọn phòng ");
            return;
        }

        if (soGio.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa nhập số ngày");
            return;
        } else if (soNgayOLai > 7) {
            this.txtSoGioSD.setText(Integer.toString(soNgayOLai * 24));
        }

        if (ktso(soGio) == false) {
            JOptionPane.showMessageDialog(this, "Số ngày phải là số");
            return;
        }

        float donGia = Float.parseFloat(this.txtDonGiaPhong.getText());
        int soGioSD = Integer.parseInt(soGio);

        if (soGioSD < 30 && soGioSD > 24) {
            soGioSD = 24;
            this.txtThanhTien.setText(Float.toString(donGia * soGioSD));
            this.txtLoaiHoaDon.setText("Hoa Don Gio");
        } else if (soNgayOLai > 7) {
            float ThanhToan = donGia * soNgayOLai * 0.8f;
            this.txtThanhTien.setText(Float.toString(ThanhToan));
            this.txtLoaiHoaDon.setText("Hoa Don Ngay");
        } else if (soGioSD < 24) {
            float ThanhToan = donGia * soGioSD;
            this.txtThanhTien.setText(Float.toString(ThanhToan));
            this.txtLoaiHoaDon.setText("Hoa Don Gio");
        } else {
            this.txtThanhTien.setText(Float.toString(donGia * soNgayOLai));
            this.txtLoaiHoaDon.setText("Hoa Don Ngay");
            this.txtSoGioSD.setText(Integer.toString(soNgayOLai * 24));
            return;
        }
    }

    public static int generateRandomIdHoaDon() {
        Random random = new Random();
        int min = 111111111; // Giá trị nhỏ nhất của khoảng số ngẫu nhiên
        int max = 999999999; // Giá trị lớn nhất của khoảng số ngẫu nhiên
        int randomNumber = random.nextInt(max - min + 1) + min;
        return randomNumber;
    }

    private void addBill(java.awt.event.ActionEvent evt) {
        DefaultTableModel dtm = (DefaultTableModel) this.tblHoaDon.getModel();
        int setID = generateRandomIdHoaDon();
        String loaiPhong = this.txtLoaiPhong.getText();
        String donGia = this.txtDonGiaPhong.getText();
        String soGio = this.txtSoGioSD.getText();
        String ngayNhanPhong = this.txtNgayDen.getText();
        String hoaDon = this.txtLoaiHoaDon.getText();
        String ngayTraPhong = this.txtNgayTraPhong.getText();
        String maHoaDon = this.txtMaHoaDon.getText();
        String tenKhachHang = this.txtTenKhachHang.getText();
        String ngayLapHoaDon = this.txtNgayLapHoaDon.getText();
        String thanhTien = this.txtThanhTien.getText();

        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate dateNhan = LocalDate.parse(ngayNhanPhong, dateTimeFormatter);
        LocalDate dateTra = LocalDate.parse(ngayTraPhong, dateTimeFormatter);

        int dateNhanInt = dateNhan.getDayOfMonth();
        int dateTraInt = dateTra.getDayOfMonth();

        int calculationDate = dateTraInt - dateNhanInt;

        if (thanhTien.equals("")) {
            JOptionPane.showMessageDialog(this, "Chưa thành tiền");
            return;
        }

        Connection conn = CSDL.Database.ConnectDatabase();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Loi ket noi");
            return;
        }
        String soPhong = this.txtSoPhong.getText();
        String sql = "insert into phong_" + soPhong
                + "(ID, loaiphong, donGia, soGio, hoaDon, ngayNhan, ngayTra, maHoaDon, tenKhachHang, ngayLapHoaDon, thanhTien, soNgayO) "
                + " values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement stm;
        try {
            stm = conn.prepareStatement(sql);
            stm.setInt(1, setID);
            stm.setString(2, loaiPhong);
            stm.setFloat(3, Float.parseFloat(donGia));
            stm.setInt(4, Integer.parseInt(soGio));
            stm.setString(5, hoaDon);
            stm.setString(6, ngayNhanPhong);
            stm.setString(7, ngayTraPhong);
            stm.setInt(8, Integer.parseInt(maHoaDon));
            stm.setString(9, tenKhachHang);
            stm.setString(10, ngayLapHoaDon);
            stm.setFloat(11, Float.parseFloat(thanhTien));
            stm.setInt(12, calculationDate);

            int n = stm.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmDKPhong.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi sql " + ex.getMessage());
            return;
        }

        HienThiDSHoaDon();

        this.txtLoaiPhong.setText("");
        this.txtDonGiaPhong.setText("");
        this.txtSoGioSD.setText("");
        this.txtLoaiHoaDon.setText("");
        this.txtNgayDen.setText("");
        this.txtNgayTraPhong.setText("");
        this.txtMaHoaDon.setText("");
        this.txtTenKhachHang.setText("");
        this.txtNgayLapHoaDon.setText("");
        this.txtThanhTien.setText("");

        HienThiDSPhong();

    }// GEN-LAST:event_btnThemMonHoaDonActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {

        this.txtLoaiPhong.setText("");
        this.txtDonGiaPhong.setText("");
        this.txtSoGioSD.setText("");
        this.txtLoaiHoaDon.setText("");
        this.txtNgayDen.setText("");
        this.txtNgayTraPhong.setText("");
        this.txtMaHoaDon.setText("");
        this.txtTenKhachHang.setText("");
        this.txtNgayLapHoaDon.setText("");
        this.txtThanhTien.setText("");

        HienThiDSPhong();
    }

    private void btnTongTienActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTongTienActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) this.tblHoaDon.getModel();
        int row = dtm.getRowCount();
        float tongtien = 0f;
        for (int i = 0; i < row; i++) {
            String x = (String) this.tblHoaDon.getValueAt(i, 10).toString();
            float xx = Float.parseFloat(x);
            tongtien += xx;
        }
        this.txtTongTien.setText(Float.toString(tongtien));

        for (int i = 0; i < row; i++) {

            Integer id = (Integer) this.tblHoaDon.getValueAt(i, 0);

            String loaiPhong = (String) this.tblHoaDon.getValueAt(i, 1);

            String donGiaStr = (String) this.tblHoaDon.getValueAt(i, 2);
            float donGiaObject = Float.parseFloat(donGiaStr);

            String soGioStr = (String) this.tblHoaDon.getValueAt(i, 3);
            Integer soGioObject = Integer.parseInt(soGioStr);

            String loaiHoaDon = (String) this.tblHoaDon.getValueAt(i, 4);
            String ngayNhanPhong = (String) this.tblHoaDon.getValueAt(i, 5);
            String ngayTraPhong = (String) this.tblHoaDon.getValueAt(i, 6);

            String maHoaDonStr = (String) this.tblHoaDon.getValueAt(i, 7);
            Integer maHoaDon = Integer.parseInt(maHoaDonStr);

            String tenKhachHang = (String) this.tblHoaDon.getValueAt(i, 8);
            String ngayLapHoaDon = (String) this.tblHoaDon.getValueAt(i, 9);

            String thanhTienStr = (String) this.tblHoaDon.getValueAt(i, 10);
            float thanhTien = Float.parseFloat(thanhTienStr);

            Integer calculation = (Integer) this.tblHoaDon.getValueAt(i, 11);

            Connection conn = CSDL.Database.ConnectDatabase();
            if (conn == null) {
                JOptionPane.showMessageDialog(this, "Loi ket noi");
                return;
            }
            String sql = "insert into thong_ke(ID, loaiPhong, donGia, soGio, hoaDon, ngayNhan, ngayTra, maHoaDon, tenKhachHang, ngayLapHoaDon, thanhTien, soNgayO)"
                    + " values(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

            PreparedStatement stm;
            try {
                stm = conn.prepareStatement(sql);
                stm = conn.prepareStatement(sql);
                stm.setInt(1, id);
                stm.setString(2, loaiPhong);
                stm.setFloat(3, donGiaObject);
                stm.setInt(4, soGioObject);
                stm.setString(5, loaiHoaDon);
                stm.setString(6, ngayNhanPhong);
                stm.setString(7, ngayTraPhong);
                stm.setInt(8, maHoaDon);
                stm.setString(9, tenKhachHang);
                stm.setString(10, ngayLapHoaDon);
                stm.setFloat(11, thanhTien);
                stm.setInt(12, calculation);
                stm.executeUpdate();

            } catch (SQLException ex) {
                Logger.getLogger(frmDKPhong.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Loi sql " + ex.getMessage());
                return;
            }
        }
    }// GEN-LAST:event_btnTongTienActionPerformed

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnThanhToanActionPerformed
        // TODO add your handling code here:
        String tt = this.txtTongTien.getText();
        if (tt.equals("") || Float.parseFloat(tt) == 0) {
            JOptionPane.showMessageDialog(this, "Thanh toán thất bại");
            return;
        }
        frmThanhToan thanhtoan = new frmThanhToan();
        thanhtoan.chonmon = this;
        thanhtoan.SB(this.txtSoPhong.getText());
        thanhtoan.setVisible(true);
    }// GEN-LAST:event_btnThanhToanActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }// GEN-LAST:event_formWindowOpened

    private void btnDSHoaDonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDSHoaDonActionPerformed
        // TODO add your handling code here:
        HienThiDSHoaDon();
    }// GEN-LAST:event_btnDSHoaDonActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int i = this.tblHoaDon.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this, "Chưa chọn hoa don cần xóa");
            return;
        } else {
            Connection cnn = CSDL.Database.ConnectDatabase();
            if (cnn == null) {
                JOptionPane.showMessageDialog(this, "Ket noi that bai !!!");
                return;
            }
            String soPhong = this.txtSoPhong.getText();
            String sql = "DELETE FROM phong_" + soPhong
                    + " WHERE ID=?";
            try {
                DefaultTableModel dtm = (DefaultTableModel) this.tblHoaDon.getModel();
                int id = (int) dtm.getValueAt(i, 0);
                PreparedStatement stm = cnn.prepareStatement(sql);
                stm.setInt(1, id);
                int n = stm.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    HienThiDSHoaDon();
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Loi SQL");
                Logger.getLogger(frmDKPhong.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }// GEN-LAST:event_btnXoaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection conn = CSDL.Database.ConnectDatabase();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Loi ket noi");
            return;
        }
        int hoi = JOptionPane.showConfirmDialog(this, "Bạn sẽ bị mất hết dữ liệu.\nChắc chắn xóa ??", "Thông báo !!!",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (hoi == JOptionPane.YES_OPTION) {
            String soPhong = this.txtSoPhong.getText();
            String sql = "delete from phong_" + soPhong;

            try {
                PreparedStatement stm = conn.prepareStatement(sql);
                int n = stm.executeUpdate();
                if (n > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa hết thành công");
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmThanhToan.class.getName()).log(Level.SEVERE, null, ex);
            }

            String sqll = "ALTER TABLE phong_" + soPhong + " AUTO_INCREMENT = 1";

            try {
                PreparedStatement stm = conn.prepareStatement(sqll);
                stm.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(frmThanhToan.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Lôi sql " + ex.getMessage());
            }
            HienThiDSHoaDon();
        }

    }// GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:

    }// GEN-LAST:event_formWindowClosed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        Connection conn = CSDL.Database.ConnectDatabase();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Loi ket noi");
            return;
        }
        String soPhong = this.txtSoPhong.getText();
        String sql = "select * from phong_" + soPhong;

        try {
            PreparedStatement stm = conn.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) this.tblHoaDon.getModel();
            dtm.setNumRows(0);
            int dem = 0;
            while (rs.next()) {
                dem++;
            }
            if (dem == 0) {
                phongKhachSan.VangKhach(soPhong);
                this.dispose();
            } else {
                phongKhachSan.CoKhach(soPhong);
                this.dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmDKPhong.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi sql " + ex.getMessage());
            return;
        }

    }// GEN-LAST:event_btnDongActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Connection conn = CSDL.Database.ConnectDatabase();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Loi ket noi");
            return;
        }
        String soPhong = this.txtSoPhong.getText();
        String sql = "select * from phong_" + soPhong;

        try {
            PreparedStatement stm = conn.prepareStatement(sql);
            ResultSet rs = stm.executeQuery();
            DefaultTableModel dtm = (DefaultTableModel) this.tblHoaDon.getModel();
            dtm.setNumRows(0);
            int dem = 0;
            while (rs.next()) {
                dem++;
            }
            if (dem == 0) {
                phongKhachSan.VangKhach(soPhong);
                this.dispose();
            } else {
                phongKhachSan.CoKhach(soPhong);
                this.dispose();
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmDKPhong.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Loi sql " + ex.getMessage());
            return;
        }
    }// GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        frmLuaChonNguoiDung chon = new frmLuaChonNguoiDung();
        chon.setVisible(true);
        this.dispose();
    }// GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }// GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDKPhong.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDKPhong.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDKPhong.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDKPhong.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDKPhong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDSHoaDon;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThanhTien;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JButton btnThemHoaDon;
    private javax.swing.JButton btnTongTien;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblGia;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtDonGiaPhong;
    private javax.swing.JTextField txtLoaiHoaDon;
    private javax.swing.JTextField txtLoaiPhong;
    private javax.swing.JTextField txtMaHoaDon;
    private javax.swing.JTextField txtNgayDen;
    private javax.swing.JTextField txtNgayLapHoaDon;
    private javax.swing.JTextField txtNgayTraPhong;
    private javax.swing.JTextField txtSoGioSD;
    private javax.swing.JLabel txtSoPhong;
    private javax.swing.JTextField txtTenKhachHang;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

    public void getLoaiPhongRemote() {
        txtLoaiPhong.getText();
    }

    public void getDonGiaRemote() {
        txtDonGiaPhong.getText();
    }

    public void getLoaiHoaDonRemote() {
        txtLoaiHoaDon.getText();
    }

    public void getMaHoaDonRemote() {
        txtMaHoaDon.getText();
    }

    public void getNgayDenRemote() {
        txtNgayDen.getText();
    }

    public void getNgayDiRemote() {
        txtNgayTraPhong.getText();
    }

    public void getNgayLapHoaDonRemote() {
        txtNgayLapHoaDon.getText();
    }

    public void getSoGioSDRemote() {
        txtSoGioSD.getText();
    }

    public void getSoPhongRemote() {
        txtSoPhong.getText();
    }

    public void getTenKhachHangRemote() {
        txtTenKhachHang.getText();
    }

    public void getThanhTienRemote() {
        txtThanhTien.getText();
    }

    public void getTongTienRemote() {
        txtTongTien.getText();
    }

}
